name: "Check Changes"
description: "Check if there are changes in specific directories"

outputs:
  migrations_changed:
    description: "Are migrations changed?"
    value: ${{ steps.changes.outputs.migrations_changed }}
  infrastructure_changed:
    description: "Is infrastructure changed?"
    value: ${{ steps.changes.outputs.infrastructure_changed }}

runs:
  using: "composite"
  steps:
    - name: Check changes
      id: changes
      run: |
        chmod +x .github/actions/check-changes/check-changes.sh
        .github/actions/check-changes/check-changes.sh
      shell: bash
