on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  issues: write
  contents: write
  pull-requests: write

name: check-changed-files

jobs:
  check-changed-files:
    runs-on: ubuntu-latest
    steps:
      - name: Check changed files
        id: changed-files
        uses: simenkristoffers1/release-please/.github/actions/changed-files@main
        with:
          directory: assistant
          patterns: "*.sql,*.md,*.json,*.cs"
          base-sha: HEAD~1

      - name: Debug
        if: ${{ steps.changed-files.outputs.files }}
        run: |
          echo ${{ steps.changed-files.outputs.files }}
