name: Deploy Project C to Staging

on:
  push:
    tags:
      - "v*.*.*"
  release:
    types: [created]

jobs:
  deploy-staging:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
