name: Deploy Project C to Staging

on:
  push:
    tags:
      - "project-c@v*.*.*"
  release:
    types: [created]

jobs:
  deploy-staging:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Staging
        run: |
          echo "Deploying Project C version ${{ github.event.release.tag_name }} to staging..."
