on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  issues: write
  contents: write
  pull-requests: write

name: release-please

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Check changes
        id: check-changes-1
        uses: simenkristoffers1/release-please/.github/actions/check-changes@main

      - name: Debug check changes
        run: |
          echo migrations_changed: ${{ steps.check-changes-1.outputs.migrations_changed }}
          echo infrastructure_changed: ${{ steps.check-changes-1.outputs.infrastructure_changed }}

      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.PAT }}
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json

      - name: Debug release
        run: |
          echo releases_created: ${{ steps.release.outputs.releases_created }}
          echo assistant--release_created: ${{ steps.release.outputs['assistant--release_created'] }}
          echo chat-ui--release_created: ${{ steps.release.outputs['chat-ui--release_created'] }}
          echo knowledge-search--release_created: ${{ steps.release.outputs['knowledge-search--release_created'] }}
          echo paths_released: ${{ steps.release.outputs.paths_released }}
          echo prs_created: ${{ steps.release.outputs.prs_created }}
          echo pr: ${{ steps.release.outputs.pr }}
          echo prs: ${{ steps.release.outputs.prs }}

      - name: Was released
        if: ${{ steps.release.outputs.releases_created == 'true' }}
        run: |
          echo "Was released"

      - uses: actions/checkout@v4
        if: ${{ steps.release.outputs.releases_created == 'true' }}

      - name: Check changes
        id: check-changes
        uses: simenkristoffers1/release-please/.github/actions/check-changes@main
        if: ${{ steps.release.outputs.releases_created == 'true' }}

      - name: Infrastructure changes
        if: ${{ steps.check-changes.outputs.infrastructure_changed == 'true' }}
        run: |
          echo "Infrastructure changes"

      - name: Migrations changes
        if: ${{ steps.check-changes.outputs.migrations_changed == 'true' }}
        run: |
          echo "Migrations changes"

      - name: Assistant release
        if: ${{ steps.release.outputs['assistant--release_created'] == 'true' }}
        run: |
          echo "Assistant release"

      - name: Chat UI release
        if: ${{ steps.release.outputs['chat-ui--release_created'] == 'true' }}
        run: |
          echo "Chat UI release"

      - name: Knowledge Search release
        if: ${{ steps.release.outputs['knowledge-search--release_created'] == 'true' }}
        run: |
          echo "Knowledge Search release"
