on:
  workflow_dispatch:
  push:
    branches:
      - main

defaults:
  run:
    working-directory: project-a

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v4
      - id: changed-files
        uses: simenkristoffers1/release-please/.github/actions/changed-files@main
        with:
          directory: "project-a"
          patterns: "*.js,*.md"
          base-sha: fd7a0e8a1e2f4ef6b4dd53b6131b432cfa44b704

      - run: echo "${{ steps.changed-files.outputs.changed-files }}"
