on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v4
      - id: changed-files
        uses: simenkristoffers1/release-please/.github/actions/changed-files@feafd22db8dfb6b03ad2deb9b8254ccd6ff21da9
        with:
          directory: "project-a"
          pattern: "*.js"
      - run: echo ${{ steps.changed-files.outputs.changed-files }}
