name: Changed Files
description: Get the changed files in a specific directory

inputs:
  directory:
    description: The directory to get the changed files from
  pattern:
    description: The pattern to match the changed files
    default: "*"
  base_sha:
    description: The base SHA to compare against
    default: HEAD~1

outputs:
  changed-files:
    description: The list of changed files
    value: ${{ steps.changes.outputs.changed-files }}

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Get changed files
      id: changes
      run: |
        DIFF=$(git diff --name-only ${{ inputs.base_sha }}..HEAD)
        echo "DIFF: $DIFF"
        CHANGED_FILES=$(git diff --name-only ${{ inputs.base_sha }}..HEAD -- '${{ inputs.directory }}/*' | grep -E ${{ inputs.pattern }})
        if [ -n "$CHANGED_FILES" ]; then
          echo "Changed files: $CHANGED_FILES"
          echo "changed-files=$(echo $CHANGED_FILES)" >> "$GITHUB_OUTPUT"
        else
          echo "No changed files"
          echo "changed-files=" >> "$GITHUB_OUTPUT"
        fi
      shell: bash
