name: "Find Changed Files"
description: "Get a list of changed files in a specific directory matching a pattern."

inputs:
  directory:
    description: "The directory to check for changes (e.g., src)."
    required: false
    default: "."
  patterns:
    description: 'A comma-delimited string of filename patterns (e.g., "*.js,*.css").'
    required: true
    default: "*"
  base_sha:
    description: "The base SHA to compare against"
    required: true
    default: fd7a0e8a1e2f4ef6b4dd53b6131b432cfa44b704

outputs:
  changed-files:
    description: "A newline-separated string of the changed files."
    value: ${{ steps.get_changes.outputs.files }}

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        sparse-checkout: ${{ inputs.directory }}
        fetch-depth: 0

    - name: Get changed files
      id: get_changes
      shell: bash
      run: |
        IFS=',' read -r -a pattern_array <<< "${{ inputs.patterns }}"

        # Final array to hold the full pathspecs.
        pathspec_array=()
        for pattern in "${pattern_array[@]}"; do
            # Trim leading/trailing whitespace from each pattern (e.g., " *.js " -> "*.js").
            trimmed_pattern=$(echo "$pattern" | xargs)
            # Add the directory and cleaned pattern to the array, ignoring empty entries.
            if [[ -n "$trimmed_pattern" ]]; then
                pathspec_array+=("$trimmed_pattern")
            fi
        done

        # Combine directory and pattern into a pathspec for git
        echo "ℹ️ Checking for changed files with pathspecs: ${pathspec_array[@]}"

        # Pass the array of pathspecs to git diff. The quotes are essential.
        CHANGED_FILES=$(git diff --name-only ${{ inputs.base_sha }}..HEAD -- "${pathspec_array[@]}")

        if [[ -n "$CHANGED_FILES" ]]; then
          echo "✅ Found changed files:"
          echo "$CHANGED_FILES"
          # Use a heredoc to correctly handle multi-line output and filenames with spaces
          echo 'files<<EOF' >> "$GITHUB_OUTPUT"
          echo "$CHANGED_FILES" >> "$GITHUB_OUTPUT"
          echo 'EOF' >> "$GITHUB_OUTPUT"
        else
          echo "ℹ️ No changed files found for the given pathspec."
          echo "files=" >> "$GITHUB_OUTPUT"
        fi
