name: "Find Changed Files"
description: "Get a list of changed files in a specific directory matching a pattern."

inputs:
  directory:
    description: "The directory to check for changes (e.g., src)."
    required: false
    default: "."
  patterns:
    description: 'A comma-delimited string of filename patterns (e.g., "*.js,*.css").'
    required: true
    default: "*"
  base-sha:
    description: "The base SHA to compare against"
    required: true
    default: HEAD~1

outputs:
  files:
    description: "A newline-separated string of the changed files."
    value: ${{ steps.get-changed-files.outputs.files }}

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
      with:
        clean: false
        sparse-checkout: |
          .github/actions/changed-files

    - id: get-changed-files
      env:
        PATTERN_ARRAY: ${{ inputs.patterns }}
        DIRECTORY: ${{ inputs.directory }}
        BASE_SHA: ${{ inputs.base-sha }}
      run: |
        chmod +x .github/actions/changed-files/changed-files.sh
        .github/actions/changed-files/changed-files.sh
      shell: bash
